blueprint:
  name: Sync two switches (PacoCT)
  description: >
    Keeps two switch entities synchronized bidirectionally.
    When one switch changes state, the other is updated to match,
    while preventing feedback loops.
  domain: automation
  source_url: https://github.com/PacoCT/homeassistant-blueprints/blob/main/blueprints/automation/paco/sync_two_switches.yaml

input:
  switch_object1:
    name: Switch 1
    selector:
      entity:
        domain: switch

  switch_object2:
    name: Switch 2
    selector:
      entity:
        domain: switch

variables:
  sw1: !input switch_object1
  sw2: !input switch_object2

trigger:
  - platform: state
    entity_id: !input switch_object1

  - platform: state
    entity_id: !input switch_object2

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.context.parent_id is none }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: >
                {{ sw2 if trigger.entity_id == sw1 else sw1 }}

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: >
                {{ sw2 if trigger.entity_id == sw1 else sw1 }}

mode: parallel
